### ISSUE TITLE
Add small input dataset for testing

### ISSUE THREAD

**Issue by marcodelapierre** [Sydney-Informatics-Hub/IndexReferenceFasta-nf#1]
Hi @georgiesamaha ,

may I suggest you include a small testing dataset in the repo?

It does not have to output any meaningful data, but just enable executing the whole pipeline to the end, using a pre-canned provided script.
Ideally it be small enough to run say under 5 minutes, to allow for quick testing of both 1. pipeline logical correctness and 2. new deployments to infrastructures and platforms.

**Comment by georgiesamaha** [comment]
Hi @marcodelapierre! Thank you for the suggestion. I have created and added a subset [fasta file](https://github.com/Sydney-Informatics-Hub/IndexReferenceFasta-nf/blob/main/testData/testHg38.fa) for testing. 

Have also added gadi and nimbus config files :)
